<a href="https://colab.research.google.com/github/tahiyat-rafi/Introduction-to-deep-learning-/blob/main/pytorch_funamentals_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


In [3]:
#scalar
scalar=torch.tensor(9)
scalar

tensor(9)

In [4]:
scalar.shape

torch.Size([])

In [5]:
scalar.ndim

0

In [6]:
#get the item back
scalar.item()

9

In [7]:
#vector
vector=torch.tensor([2,4,7])

In [8]:
#dimension is like the rank of a tensor
#shape is the total number of elements
vector.ndim

1

In [9]:
vector.shape

torch.Size([3])

In [10]:
vector[2]
#requires only one index to find out the element hence dim=1

tensor(7)

In [11]:
#matrix
matrix=torch.tensor([[2,4,6],
                    [8,8,1],
                    [5,2,4]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([3, 3])

In [14]:
matrix[0]

tensor([2, 4, 6])

In [15]:
matrix[1]

tensor([8, 8, 1])

In [16]:
matrix[2]

tensor([5, 2, 4])

In [17]:
matrix[0][0]

tensor(2)

In [18]:
matrix[0][1]

tensor(4)

In [19]:
matrix[2][0]
#requires 2 index to find individual elements hence dim=2

tensor(5)

In [20]:
#tensor
tensor=torch.tensor([[[2,4,7],
                      [3,7,1],
                      [2,1,0]]])

In [21]:
tensor.ndim

3

In [36]:
tensor.shape
#means 1 3*3 tensor

torch.Size([1, 3, 3])

In [23]:
tensor[0]

tensor([[2, 4, 7],
        [3, 7, 1],
        [2, 1, 0]])

In [24]:
tensor[0][0]

tensor([2, 4, 7])

In [25]:
tensor[0][1]

tensor([3, 7, 1])

In [26]:
tensor[0][2]

tensor([2, 1, 0])

In [27]:
tensor[0][2][1].item()
#requires 3 index to find individual elements hence dim=3

1

In [28]:
t=torch.tensor([[[[[2,3]]]]])
t.shape

torch.Size([1, 1, 1, 1, 2])

In [29]:
t.ndim

5

In [30]:
t[0][0][0][0][1].item()
#number of entities in the shape output is it's dimension.

3

#random tensors

In [31]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.2585, 0.3640, 0.8903, 0.5748],
        [0.5231, 0.7876, 0.5863, 0.1576],
        [0.2872, 0.5654, 0.2977, 0.4190]])

In [32]:
random_tensor.ndim

2

In [33]:
rt=torch.rand(size=(3,224,224))
#using "size" or not, either is good

In [34]:
zeros=torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [35]:
ones=torch.ones(size=(3,3))
ones,ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)